export const projectsGeneralList = [
  {
    title: "ShopSeeker",
    description: "Personal Project to implement a better way to append all my POD shops as digital creator (front+back)",
    image: "/img/projects/dev/shopSeeker.png",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Check Site",
    link2: "https://github.com/Raphoto1/shopseeker-fullstack",
    link2Title: "Github",
  },
  {
    title: "GameCall",
    description: "ReactNative App focused on connect gamers from different platforms",
    image: "/img/projects/dev/gamecall.png",
    link1: "https://creativerafa.com/Assets/Projects/Dev/application-bbd42573-725d-4fca-ad65-c719df5a7965.apk",
    link1Title: "Download Apk",
    link2: "https://github.com/Raphoto1/finalDesarrolloApps",
    link2Title: "Github",
  },
  {
    title: "Oston Brazil Dev",
    description: "App testing",
    image: "/img/projects/Vfx/Oston.png",
    link1: "https://oston.io/",
    link1Title: "Oston",
    link2: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link2Title: "null",
  },
  {
    title: "IZO Academy Spain",
    description: "Edition and Mograph for educational content",
    image: "/img/projects/Vfx/Izo.png",
    link1: "https://academy.izo.es/",
    link1Title: "Izo Academy",
    link2: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link2Title: "Samples",
  },
  {
    title: "Oston Brazil",
    description: "Social media promo content",
    image: "/img/projects/Vfx/Oston.png",
    link1: "https://oston.io/",
    link1Title: "Oston",
    link2: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link2Title: "Samples",
  },
  {
    title: "International Chamber of Comerce",
    description: "15mts of led screen mapping and design content",
    image: "/img/projects/Vfx/ICC.jpg",
    link1: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link1Title: "Samples",
    link2: "https://www.google.com/",
    link2Title: "null",
  },
  {
    title: "Tu cara me suena(TV show)",
    description: "Screen content creatioin for tv Show",
    image: "/img/projects/Vfx/tcms7.jpg",
    link1: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link1Title: "Samples",
    link2: "https://www.google.com/",
    link2Title: "null",
  },
  {
    title: "Peace and war",
    description: "It is incredible the way a flower can change its meaning and create a message, in the midst of war, peace will always find its way.",
    image: "/img/projects/arts/Peace.jpg",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/660c158c3a8f514ca3b76ddc",
    link2Title: "Design",
  },
  {
    title: "Maps Series",
    description: "maps are echoes of our history",
    image: "/img/projects/arts/displate.png",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/65bbcc32752f9330d42b6e48",
    link2Title: "Design",
  },
  {
    title: "Flamingo",
    description: "This is a series of animals for children but in the end we are all children inside",
    image: "/img/projects/arts/FlamingoToteBag.jpg",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/66994f56314d9394667f0c13",
    link2Title: "Design",
  },
];

export const projectsDevList = [
  {
    title: "ShopSeeker",
    description: "Personal Project to implement a better way to append all my POD shops as digital creator (front+back)",
    image: "/img/projects/dev/shopSeeker.png",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Check Site",
    link2: "https://github.com/Raphoto1/shopseeker-fullstack",
    link2Title: "Github",
  },
  {
    title: "GameCall",
    description: "ReactNative App focused on connect gamers from different platforms",
    image: "/img/projects/dev/gamecall.png",
    link1: "https://creativerafa.com/Assets/Projects/Dev/application-bbd42573-725d-4fca-ad65-c719df5a7965.apk",
    link1Title: "Download Apk",
    link2: "https://github.com/Raphoto1/finalDesarrolloApps",
    link2Title: "Github",
  },
    {
    title: "Arcidrade",
    description: "NextJs Fullstack app focused on connect Doctors with Institutions from all over the world",
    image: "/img/projects/dev/arcidrade.png",
    link1: "https://www.arcidrade.com/",
    link1Title: "Check Site",
    link2: "https://github.com/Raphoto1/finalDesarrolloApps",
    link2Title: "null",
  },
        {
    title: "Pacho Lopez Y la cumbia mestiza",
    description: "NextJs Fullstack for Music Band",
    image: "/img/projects/dev/pacho.png",
    link1: "https://pacholopez.co/",
    link1Title: "Check Site",
    link2: "https://github.com/Raphoto1/finalDesarrolloApps",
    link2Title: "null",
  },
                {
    title: "Grupo GS Capital",
    description: "NextJs Fullstack for financial services",
    image: "/img/projects/dev/gscapital.png",
    link1: "https://grupogscapital.com/",
    link1Title: "Check Site",
    link2: "https://github.com/Raphoto1/finalDesarrolloApps",
    link2Title: "null",
  },
];

export const projectsVfxList = [
  {
    title: "IZO Academy Spain",
    description: "Edition and Mograph for educational content",
    image: "/img/projects/Vfx/Izo.png",
    link1: "https://academy.izo.es/",
    link1Title: "Izo Academy",
    link2: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link2Title: "Samples",
  },
  {
    title: "Oston Brazil",
    description: "Social media promo content",
    image: "/img/projects/Vfx/Oston.png",
    link1: "https://oston.io/",
    link1Title: "Oston",
    link2: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link2Title: "Samples",
  },
  {
    title: "International Chamber of Comerce",
    description: "15mts of led screen mapping and design content",
    image: "/img/projects/Vfx/ICC.jpg",
    link1: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link1Title: "Samples",
    link2: "https://www.google.com/",
    link2Title: "null",
  },
  {
    title: "Tu cara me suena(TV show)",
    description: "Screen content creatioin for tv Show",
    image: "/img/projects/Vfx/tcms7.jpg",
    link1: "https://1drv.ms/f/s!Aocl4KmjcP_slvA6r2EEqcNFYek1Pw",
    link1Title: "Samples",
    link2: "https://www.google.com/",
    link2Title: "null",
  },
];

export const projectsArtsList = [
  {
    title: "Peace and war",
    description: "It is incredible the way a flower can change its meaning and create a message, in the midst of war, peace will always find its way.",
    image: "/img/projects/arts/Peace.jpg",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/660c158c3a8f514ca3b76ddc",
    link2Title: "Design",
  },
  {
    title: "Maps Series",
    description: "maps are echoes of our history",
    image: "/img/projects/arts/displate.png",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/65bbcc32752f9330d42b6e48",
    link2Title: "Design",
  },
  {
    title: "Flamingo",
    description: "This is a series of animals for children but in the end we are all children inside",
    image: "/img/projects/arts/FlamingoToteBag.jpg",
    link1: "https://shops.creativerafa.com/",
    link1Title: "Shops",
    link2: "https://shops.creativerafa.com/shops/66994f56314d9394667f0c13",
    link2Title: "Design",
  },
];
